# Generated by Django 5.1.4 on 2025-04-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_bonus_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_bonus_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='magic_stones',
            field=models.IntegerField(default=100),
        ),
    ]
