# Generated by Django 5.1.4 on 2025-02-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morisummon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangesession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('proposed', 'Proposed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
