# Generated by Django 5.1.4 on 2025-02-13 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morisummon', '0003_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='attack_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='attack_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('character', 'キャラクターカード'), ('support', 'サポートカード')], default='character', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='pack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='retreat_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('fire', '火'), ('water', '水'), ('thunder', '雷'), ('wind', '風'), ('earth', '土'), ('ice', '氷'), ('dark', '闇'), ('light', '光')], default='fire', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
